### PR TITLE
rubygem implementation

### PR DESCRIPTION
**Pull request by Paxa**
Author of that fork don't want it to be merged, but I think `vanilla-ujs` and `vanilla-ujs` gem should be in same repo

### CODE REVIEW

**Comment by Paxa** [comment]
Some people still use assets pipeline, how do you think they should use this?

**Comment by hauleth** [comment]
I can package it into Gem. Will do it until end of the week.

**Comment by hauleth** [comment]
Now it is fully gemified, but as @Ximik is owner of the RubyGem package it is accessible only via GitHub.

**Comment by Ximik** [comment]
If it's actively again, then maybe i'll move the gem to you?

**Comment by hauleth** [comment]
I will check against your changes. It should work the same.

**Comment by walterdavis** [comment]
I'm working on a patch to the Readme right now to include the Gem usage instructions

**Comment by hauleth** [comment]
All changes should be compatible now. There is need to write tests for them, but `diff` shows no differences between your version and mine (except `disable.js` which is non-existent in yours).

**Pull request closed without merging**
