### PR TITLE
Click on nested elements inside [data-*]

### PR DESCRIPTION
**Pull request by Paxa**
* Add `matchesSelfOrParent(element, selector)`
* Fix `[data-method]`
* Fix `[data-confirm]`
* Fix `[data-disable-with]`
* Add tests for `[data-disable-with]`
* Add support for `[data-disable]` (with tests)

I'm not sure if `matchesSelfOrParent` is a good name, hopefully will not collapse with users' code

Fixes https://github.com/hauleth/vanilla-ujs/issues/34

### CODE REVIEW

**Comment by Paxa** [comment]
@hauleth I updated test dependencies to make tests works in phantomjs

**Comment by Paxa** [comment]
@hauleth Can you help me to make approvals/lgtm pass? :)

**Comment by hauleth** [comment]
Could you please ignore and remove Mocha and Sinon from repo? it is 30k lines that we absolutely do not need.

**Comment by Paxa** [comment]
@hauleth Done

**Comment by Paxa** [comment]
@hauleth Done

**Comment by Paxa** [comment]
Since rails 5.1, it includes ujs without dependencies. Should this project be marked as deprecated? (but I find it useful for non-rails apps)

**Comment by hauleth** [comment]
LGTM

**Comment by hauleth** [comment]
I think I will just find another maintainer as I have stopped working in Rails and I have no need for it. Deprecation is also one of the solutions.

**Pull request merged**
