### PR TITLE
Rails Controller not properly recognizing LiteAjax requests as "JS"

### PR DESCRIPTION
**Pull request by walterdavis**
LiteAjax does not set an Accept header, and thus does not trigger Rails' request identification mechanism. This causes remote actions to be recognized as "\*/\*" rather than "JS", which causes the format to be wrong, and the wrong template to be loaded, as well as an issue with redirect after destroy actions.

The attached PR fixes this, but I would appreciate some guidance as to whether it goes too far. Are there cases in this library (or alternate uses of LiteAjax) where a different response would be needed? Is this too strong a preference for one usage for it to become the default, as I have it here?

Thanks,

Walter

### CODE REVIEW

**Comment by hauleth** [comment]
LGTM

**Comment by scarfacedeb** [comment]
@hauleth Could you clarify when are you going to push it into rubygems.org?

**Comment by hauleth** [comment]
@scarfacedeb sorry, forgot. Should be released now.

**Comment by scarfacedeb** [comment]
@hauleth thank you! :v:

**Pull request merged**
